Repository brandonlam4237/CSC322_Project, pull requests merged in 2023-05, with the labels that each got.

#39 Feature/builds
  README.md
  client/src/components/ProductCard.tsx
  client/src/contexts/PartsListContext.tsx
  client/src/pages/PartPicker.tsx
  client/src/pages/ProductDetail.jsx
  client/src/pages/Products.tsx
  client/src/scss/partpicker.scss
  client/src/services/apiClient.tsx
  server/auth/serializers.py
  server/auth/views.py
  server/items/fixtures/primary/ram-primary.json
  server/items/fixtures/secondary/cases-secondary.json
  server/items/fixtures/secondary/cooling-secondary.json
  server/items/fixtures/secondary/gamingpc-secondary.json
  server/items/fixtures/secondary/graphics-cards-secondary.json
  server/items/fixtures/secondary/motherboards-secondary.json
  server/items/fixtures/secondary/powersupplies-secondary.json
  server/items/fixtures/secondary/processors-secondary.json
  server/items/fixtures/secondary/ram-secondary.json
  server/items/fixtures/secondary/servers-secondary.json
  server/items/fixtures/secondary/storage-secondary.json
  server/items/fixtures/secondary/workstations-secondary.json
  server/items/models.py
  server/items/serializers.py
  server/items/urls.py
  server/items/views.py
  server/scripts/fixtures.py
  server/user/models.py
  server/user/serializers.py
  server/user/urls.py
  server/user/views.py
Labels: enhancement

#52 fix: Login issue due to urlpatterns
  server/server/urls.py
Labels: bug

#64 Bugfix/issue 59 visitor see builds
  server/items/urls.py
  server/items/views.py
Labels: bug, enhancement

#75 feat: Replaced total_price to calculate discount
  server/items/models.py
  server/user/views.py
Labels: bug

#70 Feature/rejections
  client/src/components/MemoModal.tsx
  client/src/contexts/AuthContext.tsx
  client/src/pages/Login.tsx
  client/src/services/apiClient.tsx
  server/auth/serializers.py
  server/auth/urls.py
  server/auth/views.py
  server/user/admin.py
  server/user/models.py
  server/user/serializers.py
  server/user/urls.py
  server/user/views.py
Labels: enhancement
